apiVersion: v1 
kind: Service
metadata:
  name: myapp-service
spec:
  type: NodePort
  selector:
    app: myapp1 #in service selector should match watever deployment you have created
  ports:
  - port: 80 #service port
    targetPort: 80 # container port
